ALTER TABLE matches ADD COLUMN venue_name VARCHAR(100);
ALTER TABLE matches ADD COLUMN venue_city VARCHAR(100);

UPDATE matches AS m SET
  venue_name = v.venue_name,
  venue_city = v.venue_city
FROM (VALUES
  (1,   'Estadio Azteca',          'Mexico City'),
  (2,   'Estadio Akron',           'Zapopan'),
  (3,   'BMO Field',               'Toronto'),
  (4,   'SoFi Stadium',            'Inglewood'),
  (5,   'Levi''s Stadium',         'Santa Clara'),
  (6,   'MetLife Stadium',         'East Rutherford'),
  (7,   'Gillette Stadium',        'Foxborough'),
  (8,   'BC Place',                'Vancouver'),
  (9,   'NRG Stadium',             'Houston'),
  (10,  'AT&T Stadium',            'Arlington'),
  (11,  'Lincoln Financial Field', 'Philadelphia'),
  (12,  'Estadio BBVA',            'Guadalupe'),
  (13,  'Mercedes-Benz Stadium',   'Atlanta'),
  (14,  'Lumen Field',             'Seattle'),
  (15,  'Hard Rock Stadium',       'Miami Gardens'),
  (16,  'SoFi Stadium',            'Inglewood'),
  (17,  'Arrowhead Stadium',       'Kansas City'),
  (18,  'MetLife Stadium',         'East Rutherford'),
  (19,  'Gillette Stadium',        'Foxborough'),
  (20,  'NRG Stadium',             'Houston'),
  (21,  'AT&T Stadium',            'Arlington'),
  (22,  'Estadio Azteca',          'Mexico City'),
  (23,  'BMO Field',               'Toronto'),
  (24,  'Levi''s Stadium',         'Santa Clara'),
  (25,  'Mercedes-Benz Stadium',   'Atlanta'),
  (26,  'SoFi Stadium',            'Inglewood'),
  (27,  'BC Place',                'Vancouver'),
  (28,  'Estadio Akron',           'Zapopan'),
  (29,  'Lumen Field',             'Seattle'),
  (30,  'Gillette Stadium',        'Foxborough'),
  (31,  'Lincoln Financial Field', 'Philadelphia'),
  (32,  'Levi''s Stadium',         'Santa Clara'),
  (33,  'NRG Stadium',             'Houston'),
  (34,  'BMO Field',               'Toronto'),
  (35,  'Arrowhead Stadium',       'Kansas City'),
  (36,  'Estadio BBVA',            'Guadalupe'),
  (37,  'Mercedes-Benz Stadium',   'Atlanta'),
  (38,  'SoFi Stadium',            'Inglewood'),
  (39,  'Hard Rock Stadium',       'Miami Gardens'),
  (40,  'BC Place',                'Vancouver'),
  (41,  'AT&T Stadium',            'Arlington'),
  (42,  'Lincoln Financial Field', 'Philadelphia'),
  (43,  'MetLife Stadium',         'East Rutherford'),
  (44,  'Levi''s Stadium',         'Santa Clara'),
  (45,  'NRG Stadium',             'Houston'),
  (46,  'Gillette Stadium',        'Foxborough'),
  (47,  'Estadio Akron',           'Zapopan'),
  (48,  'BMO Field',               'Toronto'),
  (49,  'BC Place',                'Vancouver'),
  (50,  'Lumen Field',             'Seattle'),
  (51,  'Hard Rock Stadium',       'Miami Gardens'),
  (52,  'Mercedes-Benz Stadium',   'Atlanta'),
  (53,  'Estadio BBVA',            'Guadalupe'),
  (54,  'Estadio Azteca',          'Mexico City'),
  (55,  'MetLife Stadium',         'East Rutherford'),
  (56,  'Lincoln Financial Field', 'Philadelphia'),
  (57,  'Arrowhead Stadium',       'Kansas City'),
  (58,  'AT&T Stadium',            'Arlington'),
  (59,  'SoFi Stadium',            'Inglewood'),
  (60,  'Levi''s Stadium',         'Santa Clara'),
  (61,  'Gillette Stadium',        'Foxborough'),
  (62,  'BMO Field',               'Toronto'),
  (63,  'Lumen Field',             'Seattle'),
  (64,  'BC Place',                'Vancouver'),
  (65,  'NRG Stadium',             'Houston'),
  (66,  'Estadio Akron',           'Zapopan'),
  (67,  'MetLife Stadium',         'East Rutherford'),
  (68,  'Lincoln Financial Field', 'Philadelphia'),
  (69,  'Hard Rock Stadium',       'Miami Gardens'),
  (70,  'Mercedes-Benz Stadium',   'Atlanta'),
  (71,  'AT&T Stadium',            'Arlington'),
  (72,  'Arrowhead Stadium',       'Kansas City'),
  (73,  'SoFi Stadium',            'Inglewood'),
  (74,  'Gillette Stadium',        'Foxborough'),
  (75,  'Estadio BBVA',            'Guadalupe'),
  (76,  'NRG Stadium',             'Houston'),
  (77,  'MetLife Stadium',         'East Rutherford'),
  (78,  'AT&T Stadium',            'Arlington'),
  (79,  'Estadio Azteca',          'Mexico City'),
  (80,  'Mercedes-Benz Stadium',   'Atlanta'),
  (81,  'Levi''s Stadium',         'Santa Clara'),
  (82,  'Lumen Field',             'Seattle'),
  (83,  'BMO Field',               'Toronto'),
  (84,  'SoFi Stadium',            'Inglewood'),
  (85,  'BC Place',                'Vancouver'),
  (86,  'Hard Rock Stadium',       'Miami Gardens'),
  (87,  'Arrowhead Stadium',       'Kansas City'),
  (88,  'AT&T Stadium',            'Arlington'),
  (89,  'Lincoln Financial Field', 'Philadelphia'),
  (90,  'NRG Stadium',             'Houston'),
  (91,  'MetLife Stadium',         'East Rutherford'),
  (92,  'Estadio Azteca',          'Mexico City'),
  (93,  'AT&T Stadium',            'Arlington'),
  (94,  'Lumen Field',             'Seattle'),
  (95,  'Mercedes-Benz Stadium',   'Atlanta'),
  (96,  'BC Place',                'Vancouver'),
  (97,  'Gillette Stadium',        'Foxborough'),
  (98,  'SoFi Stadium',            'Inglewood'),
  (99,  'Hard Rock Stadium',       'Miami Gardens'),
  (100, 'Arrowhead Stadium',       'Kansas City'),
  (101, 'AT&T Stadium',            'Arlington'),
  (102, 'Mercedes-Benz Stadium',   'Atlanta'),
  (103, 'Hard Rock Stadium',       'Miami Gardens'),
  (104, 'MetLife Stadium',         'East Rutherford')
) AS v(id, venue_name, venue_city)
WHERE m.id = v.id;

ALTER TABLE matches ALTER COLUMN venue_name SET NOT NULL;
ALTER TABLE matches ALTER COLUMN venue_city SET NOT NULL;
