-- Seed World Cup 2026 teams + en/es name translations + zeroed group standings.

INSERT INTO teams (fifa_code, flag_url, group_code) VALUES
-- Group A
('MEX', 'https://flagcdn.com/w320/mx.png',     'A'),
('RSA', 'https://flagcdn.com/w320/za.png',     'A'),
('KOR', 'https://flagcdn.com/w320/kr.png',     'A'),
('CZE', 'https://flagcdn.com/w320/cz.png',     'A'),
-- Group B
('CAN', 'https://flagcdn.com/w320/ca.png',     'B'),
('BIH', 'https://flagcdn.com/w320/ba.png',     'B'),
('QAT', 'https://flagcdn.com/w320/qa.png',     'B'),
('SUI', 'https://flagcdn.com/w320/ch.png',     'B'),
-- Group C
('BRA', 'https://flagcdn.com/w320/br.png',     'C'),
('MAR', 'https://flagcdn.com/w320/ma.png',     'C'),
('HAI', 'https://flagcdn.com/w320/ht.png',     'C'),
('SCO', 'https://flagcdn.com/w320/gb-sct.png', 'C'),
-- Group D
('USA', 'https://flagcdn.com/w320/us.png',     'D'),
('PAR', 'https://flagcdn.com/w320/py.png',     'D'),
('AUS', 'https://flagcdn.com/w320/au.png',     'D'),
('TUR', 'https://flagcdn.com/w320/tr.png',     'D'),
-- Group E
('GER', 'https://flagcdn.com/w320/de.png',     'E'),
('CUW', 'https://flagcdn.com/w320/cw.png',     'E'),
('CIV', 'https://flagcdn.com/w320/ci.png',     'E'),
('ECU', 'https://flagcdn.com/w320/ec.png',     'E'),
-- Group F
('NED', 'https://flagcdn.com/w320/nl.png',     'F'),
('JPN', 'https://flagcdn.com/w320/jp.png',     'F'),
('SWE', 'https://flagcdn.com/w320/se.png',     'F'),
('TUN', 'https://flagcdn.com/w320/tn.png',     'F'),
-- Group G
('BEL', 'https://flagcdn.com/w320/be.png',     'G'),
('EGY', 'https://flagcdn.com/w320/eg.png',     'G'),
('IRN', 'https://flagcdn.com/w320/ir.png',     'G'),
('NZL', 'https://flagcdn.com/w320/nz.png',     'G'),
-- Group H
('ESP', 'https://flagcdn.com/w320/es.png',     'H'),
('CPV', 'https://flagcdn.com/w320/cv.png',     'H'),
('KSA', 'https://flagcdn.com/w320/sa.png',     'H'),
('URU', 'https://flagcdn.com/w320/uy.png',     'H'),
-- Group I
('FRA', 'https://flagcdn.com/w320/fr.png',     'I'),
('SEN', 'https://flagcdn.com/w320/sn.png',     'I'),
('IRQ', 'https://flagcdn.com/w320/iq.png',     'I'),
('NOR', 'https://flagcdn.com/w320/no.png',     'I'),
-- Group J
('ARG', 'https://flagcdn.com/w320/ar.png',     'J'),
('ALG', 'https://flagcdn.com/w320/dz.png',     'J'),
('AUT', 'https://flagcdn.com/w320/at.png',     'J'),
('JOR', 'https://flagcdn.com/w320/jo.png',     'J'),
-- Group K
('POR', 'https://flagcdn.com/w320/pt.png',     'K'),
('COD', 'https://flagcdn.com/w320/cd.png',     'K'),
('UZB', 'https://flagcdn.com/w320/uz.png',     'K'),
('COL', 'https://flagcdn.com/w320/co.png',     'K'),
-- Group L
('ENG', 'https://flagcdn.com/w320/gb-eng.png', 'L'),
('CRO', 'https://flagcdn.com/w320/hr.png',     'L'),
('GHA', 'https://flagcdn.com/w320/gh.png',     'L'),
('PAN', 'https://flagcdn.com/w320/pa.png',     'L');

INSERT INTO team_name_translations (team_fifa_code, locale, name) VALUES
-- English
('MEX', 'en', 'Mexico'),
('RSA', 'en', 'South Africa'),
('KOR', 'en', 'South Korea'),
('CZE', 'en', 'Czechia'),
('CAN', 'en', 'Canada'),
('BIH', 'en', 'Bosnia and Herzegovina'),
('QAT', 'en', 'Qatar'),
('SUI', 'en', 'Switzerland'),
('BRA', 'en', 'Brazil'),
('MAR', 'en', 'Morocco'),
('HAI', 'en', 'Haiti'),
('SCO', 'en', 'Scotland'),
('USA', 'en', 'United States'),
('PAR', 'en', 'Paraguay'),
('AUS', 'en', 'Australia'),
('TUR', 'en', 'Türkiye'),
('GER', 'en', 'Germany'),
('CUW', 'en', 'Curaçao'),
('CIV', 'en', 'Ivory Coast'),
('ECU', 'en', 'Ecuador'),
('NED', 'en', 'Netherlands'),
('JPN', 'en', 'Japan'),
('SWE', 'en', 'Sweden'),
('TUN', 'en', 'Tunisia'),
('BEL', 'en', 'Belgium'),
('EGY', 'en', 'Egypt'),
('IRN', 'en', 'Iran'),
('NZL', 'en', 'New Zealand'),
('ESP', 'en', 'Spain'),
('CPV', 'en', 'Cape Verde'),
('KSA', 'en', 'Saudi Arabia'),
('URU', 'en', 'Uruguay'),
('FRA', 'en', 'France'),
('SEN', 'en', 'Senegal'),
('IRQ', 'en', 'Iraq'),
('NOR', 'en', 'Norway'),
('ARG', 'en', 'Argentina'),
('ALG', 'en', 'Algeria'),
('AUT', 'en', 'Austria'),
('JOR', 'en', 'Jordan'),
('POR', 'en', 'Portugal'),
('COD', 'en', 'DR Congo'),
('UZB', 'en', 'Uzbekistan'),
('COL', 'en', 'Colombia'),
('ENG', 'en', 'England'),
('CRO', 'en', 'Croatia'),
('GHA', 'en', 'Ghana'),
('PAN', 'en', 'Panama'),
-- Spanish
('MEX', 'es', 'México'),
('RSA', 'es', 'Sudáfrica'),
('KOR', 'es', 'Corea del Sur'),
('CZE', 'es', 'Chequia'),
('CAN', 'es', 'Canadá'),
('BIH', 'es', 'Bosnia y Herzegovina'),
('QAT', 'es', 'Catar'),
('SUI', 'es', 'Suiza'),
('BRA', 'es', 'Brasil'),
('MAR', 'es', 'Marruecos'),
('HAI', 'es', 'Haití'),
('SCO', 'es', 'Escocia'),
('USA', 'es', 'Estados Unidos'),
('PAR', 'es', 'Paraguay'),
('AUS', 'es', 'Australia'),
('TUR', 'es', 'Turquía'),
('GER', 'es', 'Alemania'),
('CUW', 'es', 'Curazao'),
('CIV', 'es', 'Costa de Marfil'),
('ECU', 'es', 'Ecuador'),
('NED', 'es', 'Países Bajos'),
('JPN', 'es', 'Japón'),
('SWE', 'es', 'Suecia'),
('TUN', 'es', 'Túnez'),
('BEL', 'es', 'Bélgica'),
('EGY', 'es', 'Egipto'),
('IRN', 'es', 'Irán'),
('NZL', 'es', 'Nueva Zelanda'),
('ESP', 'es', 'España'),
('CPV', 'es', 'Cabo Verde'),
('KSA', 'es', 'Arabia Saudita'),
('URU', 'es', 'Uruguay'),
('FRA', 'es', 'Francia'),
('SEN', 'es', 'Senegal'),
('IRQ', 'es', 'Irak'),
('NOR', 'es', 'Noruega'),
('ARG', 'es', 'Argentina'),
('ALG', 'es', 'Argelia'),
('AUT', 'es', 'Austria'),
('JOR', 'es', 'Jordania'),
('POR', 'es', 'Portugal'),
('COD', 'es', 'RD del Congo'),
('UZB', 'es', 'Uzbekistán'),
('COL', 'es', 'Colombia'),
('ENG', 'es', 'Inglaterra'),
('CRO', 'es', 'Croacia'),
('GHA', 'es', 'Ghana'),
('PAN', 'es', 'Panamá');

INSERT INTO group_standings (
  fifa_code, group_code, position,
  matches_played, wins, draws, losses,
  goals_for, goals_against, goal_difference, points
)
SELECT t.fifa_code, t.group_code, 0, 0, 0, 0, 0, 0, 0, 0, 0
FROM teams t;
